# SpecMint golangci-lint configuration
# Simplified configuration for CI/CD compatibility

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

issues:
  exclude-use-default: false
