# SpecMint golangci-lint configuration
# Simplified configuration for CI/CD compatibility

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
  disable:
    - typecheck  # Disable explicit typecheck to avoid import resolution issues

linters-settings:
  staticcheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
