# SpecMint golangci-lint configuration
# Minimal configuration for CI/CD compatibility

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - unused
    - gofmt
    - goimports
    - misspell
  disable:
    - typecheck
    - staticcheck  # Disable staticcheck as it's causing import resolution issues

issues:
  exclude-use-default: false
