# SpecMint golangci-lint configuration
# Ultra-minimal configuration for CI/CD compatibility

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"

linters:
  # Only enable linters that don't perform type checking
  enable:
    - gofmt      # Format checking only
    - goimports  # Import organization only
    - misspell   # Spelling check only
  disable-all: true  # Explicitly disable all other linters

issues:
  exclude-use-default: false
